description: A new Flutter project.
environment:
  sdk: '>=3.4.4 <4.0.0'
version: 1.0.0+1
flutter:
  assets:
    - samples/drums/
    - samples/drums/Kick/
    - samples/drums/Plates/
    - samples/drums/Plates/China/
    - samples/drums/Plates/Crash/
    - samples/drums/Plates/Hi Hat/
    - samples/drums/Plates/Ride Cymbal/
    - samples/drums/Plates/Splash/
    - samples/drums/Snare/
    - samples/drums/Toms/
    - samples/synth/
    - samples/synth/Bass/
    - samples/synth/Lead/
    - .env
    - icons/
    - samples_manifest.json
  uses-material-design: true
dependencies:
  provider: ^6.1.1
  flutter_svg: ^2.0.9
  flutter:
    sdk: flutter
  file_picker: ^8.0.7
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  google_fonts: ^6.1.0
  flutter_dotenv: ^5.1.0
  docman: ^1.2.0
  path_provider: ^2.1.1
  ffi: ^2.1.0
  path: ^1.9.0
  share_plus: ^7.2.2
  shared_preferences: ^2.2.2
  just_audio: ^0.9.36
  connectivity_plus: ^7.0.0
  app_links: ^6.2.0
name: fortuned
publish_to: none
dev_dependencies:
  flutter_test:
    sdk: flutter
  ffigen: ^13.0.0
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "icons/app_icon.png"
  remove_alpha_ios: true
